name: farm_marketplace_seller_app
description: Seller mobile app for Farm Marketplace.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  farm_marketplace_shared_api:
    path: ../shared_api
  image_picker: ^1.1.2
  dio: ^5.7.0
  http_parser: ^4.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
